### PR TITLE
update ztf references

### PR DESCRIPTION
**Pull request by mcoughlin**
**Does this pull request make any changes to the database?**
None

Code changes that affect the database require special attention for data migration.
If your change affects the database, describe the migration plan here.

### CODE REVIEW

**Comment by lpsinger** [comment]
Would you please explain what this change does?

**Comment by mcoughlin** [comment]
Uses Frank's dedicated ToO reference limits.

**Comment by lpsinger** [comment]
Is this going to be a permanent change? If so, we need not keep the old code.

**Comment by mcoughlin** [comment]
I think that the future of this is ambiguous enough (read, political disagreement) that it's worth having the original as well for now.

**Comment by lpsinger** [comment]
OK, but the format of the output is the same? So instead of copy-pasting the entire task, can we just comment out the old code?

**Comment by mcoughlin** [comment]
yes we can do whatever you like. commented out or not, i am happy.

**Comment by lpsinger** [comment]
OK, would you please remove the new task, comment out the old scraping code, and add the new scraping code?

**Comment by lpsinger** [comment]
BTW, please rebase from master to get the latest unit test fixes.

**Comment by lpsinger** [comment]
Please rebase with master so that we can see if the unit tests pass.

**Pull request merged**
