### PR TITLE
fix error in filter schedule

### PR DESCRIPTION
**Pull request by shreyasahasram08**
The alternating and block scheduling options were switched.  Please test to verify.

### CODE REVIEW

**Comment by mcoughlin** [comment]
@shreyasahasram08  doAlternatingFilters is the block scheduler... you seeing something different?

**Comment by shreyasahasram08** [comment]
Yeah...Mansi and I were looking at this the other day, and we got the opposite schedule than what we expected when clicking 'block' or 'integrated'.  Of course there were a few filter skips around as well.  I can send you my test json files

**Comment by mcoughlin** [comment]
@shreyasahasram08 please see the new version of gwemopt to see if the fixes there have resolved this.

**Comment by lpsinger** [comment]
Is this resolved?

**Comment by shreyasahasram08** [comment]
We made some fixes in gwemopt, but they don't seem to be working properly in Skipper.  I have been unable to test locally due to some issues that I'm trying to fix now.  If Skipper is only ~ 2 days behind the marshal then the issue hasn't been resolved yet.

**Comment by lpsinger** [comment]
OK, the main thing is that this needs to be rebased and pass the unit tests.

**Comment by mcoughlin** [comment]
@shreyasahasram08 as we discussed yesterday, this problem was more one of interpretation of the schedules than anything else. Adding the adjustable minimum difference between field observations helped with this.

**Pull request closed without merging**
